package com.user.model;

public class LogisticsAssignRules {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ilar.username
     *
     * @mbg.generated Tue Sep 19 14:31:55 CST 2017
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ilar.username
     *
     * @return the value of ilar.username
     *
     * @mbg.generated Tue Sep 19 14:31:55 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ilar.username
     *
     * @param username the value for ilar.username
     *
     * @mbg.generated Tue Sep 19 14:31:55 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}